[local]
localhost

[mongodb]
mongodb-dev.tehith.online

[catalogue]
catalogue-dev.tehith.online

[redis]
redis-dev.tehith.online

[user]
user-dev.tehith.online

[cart]
cart-dev.tehith.online

[mysql]
mysql-dev.tehith.online

[shipping]
shipping-dev.tehith.online

[rabbitq]
rabbitmq-dev.tehith.online

[payment]
payment-dev.tehith.online

[frontend]
frontend-dev.tehith.online