- name: demo on datatypes
  hosts: local
  connection: local
  vars:
    PROGRAM: "DevSecOps with AWS"
    DURATION: 140
    IS_LIVE: true
    DETAILS:
      MONTHS: 4
      TRAINER: "Siva Kumar Reddy"
    TOPICS:
    - Linux
    - Shell
    - Ansible
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: |
        Program: {{ PROGRAM}}
        Duration: {{ DURATION }}
        IsLive: {{ IS_LIVE }}
        Details: {{ DETAILS }}
        Topics: {{ TOPICS }}