- name: configure shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven and mysql
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

    - name: create system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop System user"
  
  - name: Delete App Directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create App Directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete shipping Zip File
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: Download shipping Zip File
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Unarchive shipping
    ansible.builtin.Unarchive:
      src: /tmp/shipping.zip
      dest: /app
      rempte_src: yes
  
  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app
  
  - name: install dependencies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: install dependencies
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL

    - name: import shipping data
      community.mysql.mysql_db:
        state: import
        name: all
        login_host: "{{ MYSQL_HOST }}"
        login_user: root
        login_password: Roboshop@1
        target: "{{ item }}"
      loop:
      - /app/db/schema.sql
      - /app/db/app-user.sql
      - /app/db/master-data.sql

    - name: start shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes
